language: ruby
cache: bundler
bundler_args: --without development
matrix:
  include:
    - rvm: 2.2.10
    - rvm: 2.3.8
    - rvm: 2.4.6
    - rvm: 2.5.5
    - rvm: 2.6
    - rvm: ruby-head
  allow_failures:
    - rvm: 2.6
    - rvm: ruby-head

script: bundle exec rake spec
